#!/usr/bin/env bash

set -eu
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

. $(dirname $0)/lib.sh

report="$( uscan_report )"

new_version="$( echo "$report" | get_version )"

json_tmpl='
  [
    { "ref" : $ver }
  ]
'

jq -n \
  --arg ver "$new_version" \
  "$json_tmpl" \
  >&3
