#!/usr/bin/env bash

set -eu
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

. $(dirname $0)/lib.sh

dest_dir="$1"

report="$( uscan_report )"

new_version="$( echo "$report" | get_version )"
new_url="$( echo "$report" | get_url )"

json_tmpl='
  {
    "version" : { "ref" : $ver },
    "metadata" : [
      { "name": "version", "value": $ver },
      { "name": "url",     "value": $url }
    ]
  }
'

jq -n \
  --arg ver "$new_version" \
  --arg url "$new_url" \
  "$json_tmpl" \
  | tee "${dest_dir}/version" \
  >&3
